export const PROVINCE_TH_TO_EN: Record<string, string> = {
  เชียงใหม่: "Chiang Mai",
  เชียงราย: "Chiang Rai",
  แม่ฮ่องสอน: "Mae Hong Son",
  ลำพูน: "Lamphun",
  ลำปาง: "Lampang",
  แพร่: "Phrae",
  น่าน: "Nan",
  พะเยา: "Phayao",
  ตาก: "Tak",
  สุโขทัย: "Sukhothai",
  พิษณุโลก: "Phitsanulok",
  อุตรดิตถ์: "Uttaradit",
  กำแพงเพชร: "Kamphaeng Phet",
  พิจิตร: "Phichit",
  เพชรบูรณ์: "Phetchabun",
  นครสวรรค์: "Nakhon Sawan",
  อุทัยธานี: "Uthai Thani",
  ชัยนาท: "Chai Nat",
  กาญจนบุรี: "Kanchanaburi",
  ราชบุรี: "Ratchaburi",
  เพชรบุรี: "Phetchaburi",
  ประจวบคีรีขันธ์: "Prachuap Khiri Khan",
  สุพรรณบุรี: "Suphan Buri",
  นครปฐม: "Nakhon Pathom",
  สมุทรสาคร: "Samut Sakhon",
  สมุทรสงคราม: "Samut Songkhram",
  กรุงเทพมหานคร: "Bangkok Metropolis",
  นนทบุรี: "Nonthaburi",
  ปทุมธานี: "Pathum Thani",
  พระนครศรีอยุธยา: "Phra Nakhon Si Ayutthaya",
  อ่างทอง: "Ang Thong",
  ลพบุรี: "Lop Buri",
  สิงห์บุรี: "Sing Buri",
  สระบุรี: "Saraburi",
  นครนายก: "Nakhon Nayok",
  สมุทรปราการ: "Samut Prakan",
  ฉะเชิงเทรา: "Chachoengsao",
  ชลบุรี: "Chon Buri",
  ระยอง: "Rayong",
  จันทบุรี: "Chanthaburi",
  ตราด: "Trat",
  ปราจีนบุรี: "Prachin Buri",
  สระแก้ว: "Sa Kaeo",
  นครราชสีมา: "Nakhon Ratchasima",
  บุรีรัมย์: "Buri Ram",
  สุรินทร์: "Surin",
  ศรีสะเกษ: "Si Sa Ket",
  อุบลราชธานี: "Ubon Ratchathani",
  ยโสธร: "Yasothon",
  ชัยภูมิ: "Chaiyaphum",
  อำนาจเจริญ: "Amnat Charoen",
  มุกดาหาร: "Mukdahan",
  ร้อยเอ็ด: "Roi Et",
  กาฬสินธุ์: "Kalasin",
  มหาสารคาม: "Maha Sarakham",
  ขอนแก่น: "Khon Kaen",
  อุดรธานี: "Udon Thani",
  หนองคาย: "Nong Khai",
  บึงกาฬ: "Bueng Kan",
  หนองบัวลำภู: "Nong Bua Lam Phu",
  เลย: "Loei",
  สกลนคร: "Sakon Nakhon",
  นครพนม: "Nakhon Phanom",
  ชุมพร: "Chumphon",
  สุราษฎร์ธานี: "Surat Thani",
  นครศรีธรรมราช: "Nakhon Si Thammarat",
  กระบี่: "Krabi",
  พังงา: "Phangnga",
  ภูเก็ต: "Phuket",
  ตรัง: "Trang",
  พัทลุง: "Phatthalung",
  สตูล: "Satun",
  สงขลา: "Songkhla",
  ปัตตานี: "Pattani",
  ยะลา: "Yala",
  นราธิวาส: "Narathiwat",
  ระนอง: "Ranong",
};
